[package]
name = "fips204-dudect"
version = "0.1.0"
authors = ["Eric Schorn <eschorn@integritychain.com>"]
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
fips204 = { path = ".." }
dudect-bencher = "0.6"